spring.application.name=expense-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=Postgres@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true